### ISSUE TITLE
OCI Registries

### ISSUE THREAD

**Issue by christianh814** [christianh814/bekind#2]
Add the ability to install Charts that are in an OCI registry

```yaml
  - url: "oci://ghcr.io/akuity/kargo-charts/kargo"
    repo: "argo" # Ignored
    chart: "argo-cd" # Ignored
    release: "kargo"
    namespace: "kargo" 
    args: 'controller.logLevel=DEBUG'
```
