### ISSUE TITLE
Add the abilty to specify chart version

### ISSUE THREAD

**Issue by christianh814** [christianh814/bekind#3]
Just like `helm install  --version` , `bekind` config should allow users to specify version of the chart

```yaml
 - url: "https://argoproj.github.io/argo-helm"
    repo: "argo"
    chart: "argo-cd"
    release: "argocd"
    namespace: "argocd"
    version: 5.46.8 # ADD THIS
    args: 'server.ingress.enabled=true,server.ingress.hosts[0]=argocd.7f000001.nip.io,server.ingress.ingressClassName="nginx",server.ingress.https=true,server.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-passthrough"=true,server.ingress.annotations."nginx\.ingress\.kubernetes\.io/force-ssl-redirect"=true'
```

The "lack" of  `version` will mean just install the latest
